---
title: 'Problem Set 3: Instrumental Variables'
author: "Claire Duquennois"
date: ""
output:
  pdf_document:
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

***NAME:____________________________***

**Empirical Analysis using Data from Ananat (2011, AEJ:AE)**


This exercise uses data from Elizabeth Ananat's paper, "The Wrong Side(s) of the Tracks: The Causal Effects of Racial Segregation on Urban Poverty and Inequality," published in the *American Economic Journal: Applied Economics* in 2011. This paper studies how segregation has affected population characteristics and income disparity in US cities using the layout of railroad tracks as an instrumental variable. 


**Finding the data**

I have downloaded Ananat's `aej_maindata.dta` file and made it available in the RCloud assignment workspace. I downloaded this data from the AER's website which links you to the ICPSR's data repository. Anyone can sign in to get access to the replication data files. These include the typical files in a replication folder: several datasets, several .do files (which is a STATA command file), and text files with the data descriptions which tell you about the different variables included in the dataset. 


**Submission instructions:**

1) Knit your assignment in PDF.

2) **Assignment shell extra credit:** You will receive a little extra credit if your answers line up correctly with the answer positions of the template on gradescope. For this to work 

- **Work by putting your answers directly into this R markdown file that is pre-formatted for you!**

- Make sure you have ONE question and answer per page (this is how the template is structured and  allows gradescope to easily find your answers), unless the question indicated that the answer will require two pages because of large tables. 

- Your final PDF should be 24 pages. 

- You can insert needed page breaks as illustrated below

- Make sure you do not "print" the data. If you change the data, make sure you store with a structure like: newname<-modification(olddata). If you only type modification(olddata), R will display the data rather than saving your modifications


3) Upload your assignment PDF to gradescope.





\pagebreak

# Set up and opening the data

## Question: Load the have, dplyr, stargazer, lfe and ggplot2 packages and the data contained in the `aej_maindata.dta` file. Make sure it is stored as a data frame.  

**Code:**



 \pagebreak


## Question:The dataset contains many variables, some of which are not used in this exercise. Keep the following variables in the final dataset (Hint: use the `select` function in `dplyr`). 

| Name     |Description                                                             |
|----------|------------------------------------------------------------------------|
|dism1990	 |1990 dissimilarity index                                                | 
|herf      |RDI (Railroad division index)                                           |
|lenper    |Track length per square km                                              |
|povrate_w |White poverty rate 1990                                                 |
|povrate_b |Black poverty rate 1990                                                 |
|area1910  |Physical area in 1910 (1000 sq. miles)                                  |
|count1910 |Population in 1910 (1000s)                                              | 
|ethseg10  |Ethnic Dissimilariy index in 1910                                       |
|ethiso10  |Ethnic isolation index in 1910                                          |
|black1910 |Percent Black in 1910                                                   |
|passpc    |Street cars per capita 1915                                             |
|black1920 |Percent Black 1920                                                      |
|lfp1920   |Labor Force Participation 1920                                          |
|incseg    |Income segregation 1990                                                 |
|pctbk1990 |Percent Black 1990                                                      |
|manshr    |Share employed in manufacturing 1990                                    |
|pop1990   |Population in 1990                                                      |

**You can find the detailed description of each variable in the original paper. **

**Code:**


\pagebreak


# Data description: 

## Question: How many observations are contained in the data. What is the level of an observation (i.e. are observations about individuals each year? individuals seen once? Counties each year? Counties seen once? States?...) ?

**Answer:**


\pagebreak

## Question: Report summary statistics of the following variables in the dataset:"dism1990", "herf", "lenper", "povrate_w", "povrate_b". Present these summary statistics in a formatted table, you can use `stargazer` or other packages.

**Code:**

\pagebreak

# Reduced Form:

## Question: We are interested in understanding how segregation affects population characteristics and income disparity in US cities. We will focus on two outcome variables: the poverty rate for blacks and whites. Regress these two outcome variables on segregation in 1990, our explanatory variable, and interpret your results. Report robust standard errors. 

Hint 1: These exact results are reported in the second row of columns 1 and 2 of table 2. 

Hint 2: Since the units of the explanatory variable are strange, it is helpful to interpret the effect in terms of standard deviations. So instead of interpreting a one unit change in `dism1990`, interpret a  one standard deviation (0.14) change in `dism1990`. 


**Code:**

**Answer:**


\pagebreak

## Question: Explain the problem with giving a causal interpretation to the estimates you just produced. Give examples of specific confounds that might make a causal interpretation of your result problematic.

**Answer:**

\pagebreak


# Validity of the instrument:

## Question: Estimate the following regression and interpret it's coefficients, 
$$
 dism1990_i=\beta_0+\beta_1RDI_i+\beta_2 tracklength_i+\epsilon.
$$

Hint 1: These exact results are reported in the first column of the top panel of table 1.


Hint 2: Since the units of the explanatory variable are strange, it is helpful to interpret the effect in terms of standard deviations. So instead of interpreting a one unit change in `herf`, interpret a one standard deviation (0.14) change in `herf`. 

Hint 3: Make sure you report the same type of standard errors as the author. 


**Code:**

**Answer:**

\pagebreak




## Question: In the context of instrumental variables, what is this regression referred to as and why is it important? 

**Answer:**

\pagebreak


## Question: Illustrate the relationship between the RDI and segregation graphically. 

Hint: See figure 3.

**Code:**

\pagebreak


## Question: Is there a concern that this might be a weak instrument? Why would this be a problem? 

Hint: The number you want to look at has already been calculated when you ran the regression and is contained in that regression object. You can pull stuff out of a regression summary with code in the following format: summary(reg)$whatIwant

**Answer:**



\pagebreak


## Question:  Regress the following cith characteristics  on the RDI and track length: `area1910` `count1910`, `black1910`, `incseg`, `lfp1920`. Present your results and interpret your findings. Why do these results matter for answering our question of interest?  (2 pages)

Hint 1: In stargazer, add the option `omit.stat=c( "ser")` to remove the residual standard errors from the table footer so that the table fits the width of a page. 

Hint 2: Use the same type of standard errors as the author

**Code and Answer:**


\pagebreak


## Question: What are the two conditions necessary for a valid instrument? What evidence do you have that the RDI meet these conditions? Be specific in supporting this claim. 

**Answer:**

\pagebreak


## Question: Do you believe the instrument is valid? Why/why not?

**Answer:**


\pagebreak


## Question: Generate a table that estimates the effect of segregation on the poverty rate for blacks and whites by OLS and then using the RDI instrument. Make sure you report robust standard errors. How does the use of the RDI instrument change the estimated coefficients? 

Hint: these will be the exact results reported in row 2 of columns 1-4 in table 2.

**Code and Answer:**


\pagebreak


## Question: What is the reduced form equation?

**Answer:**


\pagebreak


## Question: For the two poverty rates, estimate the reduced form on all the cities and illustrate the reduced form relationships graphically. (2 pages)

**Code:**

\pagebreak

## Question: Generate a table with six columns that check whether the main results are robust to adding additional controls for city characteristics. What do you conclude? (2 pages)

Hint 1: In stargazer, add the option `omit.stat=c( "ser")` to remove the residual standard errors from the table footer so that the table fits in a page. 

Hint 2: You can choose the controls you want.  


**Code:**


**Answer:**
  

\pagebreak

# Why **Two Stage** least squares? 

Because the estimates in this paper only feature one endogenous regressor and one instrument, it is an excellent example with which to illustrate build intuition and see what the instrumental variables regressor is actually doing because in this scenario the IV estimator is exactly equal to the two stage least squares estimator ($\hat{\beta}_{IV}=\hat{\beta}_{2SLS}$).



## Question: Estimate the first stage regression and use your estimates to generate the predicted values for the explanatory variable for all the observations.

Hint: you can generate a new column in you data the gives you the predicted outcome value for each observation that is generated from a particular regression with code in the format data$newcolumn<-predict(reg_object)

**Code:**


\pagebreak


## Question: If our instrument is valid, the step above "removed" the "bad" endogenous variation from the predicted explanatory variable, keeping only the exogenous variation that is generated by the instrument. Now run the second stage by regressing our outcome variable on the predicted values generated above and the relevant controls. Compare your estimates from this regression to those generated earlier. How do they compare?

Hint: Use robust standard errors


**Code:**


**Answer:**

\pagebreak

# Yet another IV trick: Taking the "Good" variation and scaling it

## Question: Take the coefficient from you reduced form estimate and divide it by your first stage estimate. How does this value compare your earlier estimate for the main result? 

**Answer:**

 


\pagebreak



